### ISSUE TITLE
Follow good rules in css development

### ISSUE THREAD

**Issue by msn0** [allegro/selena#31]
`stylesheet.css` needs some work to make it modern-rules-compliant:

**don't select elements by tag name** (which decreases performance)

``` css
.service-info p {...}
.input-append input {...}
#show-header h1 {...}
```

**never use `!important`**

``` css
span.service-hist-wrap span.popover-open {
    border-top: 4px solid #008c00 !important;
    border-bottom: 4px solid #008c00 !important;
}

.input-append input {
    width: 150px !important;
}
```

**don't mix underscores "_" with dashes "-"** - use one of them

``` css
.service_ico {...}
span.service-hist-wrap {...}
```

**don't inline css**

``` twig
<div id="main_plot_{{ group.group_id }}" style="width: 850px; height: 450px;"></div>
```

**fix code formatting** (take a look at `.service-info` declaration)
